- name: Create Planka Postgres user
  community.postgresql.postgresql_user:
    login_host: localhost
    login_user: postgres
    login_password: '{{config.postgres_password}}'
    login_db: postgres
    name: planka
    password: '{{config.planka_postgres_password}}'
    state: present
- name: Create Planka Postgres database
  community.postgresql.postgresql_db:
    login_host: localhost
    login_user: postgres
    login_password: '{{config.postgres_password}}'
    maintenance_db: postgres
    name: planka
    owner: planka
    state: present

- name: Create Planka Docker volume
  vars:
    volume_name: homelab-planka-data
  ansible.builtin.import_tasks: ../util/create_docker_volume.yaml
- name: Start Planka Docker container
  community.docker.docker_container:
    name: homelab-planka-bootstrap
    image: ghcr.io/plankanban/planka:latest
    pull: true
    env:
      BASE_URL: https://planka.homelab.net
      DATABASE_URL: 'postgresql://planka:{{config.planka_postgres_password}}@postgres/planka'
      NODE_ENV: production
      SECRET_KEY: '{{config.planka_secret_key}}'
    volumes:
    - homelab-planka-data:/app
    - /etc/localtime:/etc/localtime:ro
    networks:
    - name: homelab-postgres-bootstrap
    published_ports:
    - 8006:1337
    auto_remove: true
    keep_volumes: false
    state: started
- name: Wait for Planka to come online
  ansible.builtin.wait_for:
    host: localhost
    port: 8006
    state: started
- name: Wait for confirmation
  ansible.builtin.pause:
    prompt: Go to https://planka.homelab.net and finish Planka setup

- name: Stop Planka Docker container
  community.docker.docker_container:
    name: homelab-planka-bootstrap
    state: absent
