watch:
  schedule: 0 9,21 * * *
  jitter: 30s
  firstCheckNotif: false
  runOnStartup: true
  healthchecks:
    baseURL: https://healthchecks.homelab.net/ping/
    uuid: 83f6999f-8f20-4efe-91f7-bc7aaf528be3
notif:
  ntfy:
    endpoint: https://ntfy.homelab.net
    topic: diun
    priority: 3
    tags:
      - whale
  webhook:
    endpoint: https://diun.homelab.net/webhook
    method: POST
    headers:
      content-type: application/json
      authorization: diun
    timeout: 10s
providers:
  docker: true
