version: '3'

services:
  postgres:
    container_name: homelab-postgres
    image: postgres:latest
    restart: unless-stopped
    volumes:
    - type: volume
      source: postgres-data
      target: /var/lib/postgresql/data
    - type: bind
      source: /etc/localtime
      target: /etc/localtime
      read_only: true
    networks:
    - homelab
    ports:
    - 5432:5432
  nextcloud:
    container_name: homelab-nextcloud
    image: nextcloud:latest
    depends_on:
    - postgres
    restart: unless-stopped
    volumes:
    - type: volume
      source: nextcloud-data
      target: /var/www/html
    - type: bind
      source: /etc/localtime
      target: /etc/localtime
      read_only: true
    networks:
    - homelab
    ports:
    - 8001:80
  gitea:
    container_name: homelab-gitea
    image: gitea/gitea:latest
    depends_on:
    - postgres
    restart: unless-stopped
    volumes:
    - type: volume
      source: gitea-data
      target: /data
    - type: bind
      source: /etc/localtime
      target: /etc/localtime
      read_only: true
    networks:
    - homelab
    ports:
    - 8002:8002
  jenkins:
    container_name: homelab-jenkins
    image: jenkins/jenkins:latest
    restart: unless-stopped
    volumes:
    - type: volume
      source: jenkins-data
      target: /var/jenkins_home
    - type: bind
      source: /etc/localtime
      target: /etc/localtime
      read_only: true
    networks:
    - homelab
    ports:
    - 8003:8080
  uptime-kuma:
    container_name: homelab-uptime-kuma
    image: louislam/uptime-kuma:latest
    restart: unless-stopped
    volumes:
    - type: volume
      source: uptime-kuma-data
      target: /app/data
    - type: bind
      source: /etc/localtime
      target: /etc/localtime
      read_only: true
    networks:
    - homelab
    ports:
    - 8004:3001
  wiki:
    container_name: homelab-wiki
    image: requarks/wiki
    restart: unless-stopped
    environment:
      DB_TYPE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: wiki
      DB_PASS: ${WIKI_POSTGRES_PASSWORD}
      DB_NAME: wiki
    volumes:
    - type: bind
      source: /etc/localtime
      target: /etc/localtime
      read_only: true
    networks:
    - homelab
    ports:
    - 8005:3000
  planka:
    container_name: homelab-planka
    image: ghcr.io/plankanban/planka:latest
    depends_on:
    - postgres
    restart: unless-stopped
    environment:
      BASE_URL: https://planka.homelab.net
      DATABASE_URL: postgresql://planka:${PLANKA_POSTGRES_PASSWORD}@postgres/planka
      NODE_ENV: production
      SECRET_KEY: ${PLANKA_SECRET_KEY}
    volumes:
    - type: volume
      source: planka-data
      target: /app
    - type: bind
      source: /etc/localtime
      target: /etc/localtime
      read_only: true
    networks:
    - homelab
    ports:
    - 8006:1337
  unbound:
    container_name: homelab-unbound
    image: unbound:latest
    depends_on:
    - postgres
    restart: unless-stopped
    environment:
      DNS_POSTGRES_PASSWORD: ${DNS_POSTGRES_PASSWORD}
    volumes:
    - type: bind
      source: /etc/localtime
      target: /etc/localtime
      read_only: true
    network_mode: host

volumes:
  postgres-data:
    name: homelab-postgres-data
    external: true
  nextcloud-data:
    name: homelab-nextcloud-data
    external: true
  gitea-data:
    name: homelab-gitea-data
    external: true
  jenkins-data:
    name: homelab-jenkins-data
    external: true
  planka-data:
    name: homelab-planka-data
    external: true
  uptime-kuma-data:
    name: homelab-uptime-kuma-data
    external: true

networks:
  homelab:
    name: homelab
