- name: Setup homelab
  hosts: citadel
  tasks:
  - name: Load JSON config
    ansible.builtin.include_vars:
      name: config
      file: config.json
  - name: Create repo temporary directory
    ansible.builtin.tempfile:
      state: directory
    register: homelab_repo
  - name: Clone git repo
    ansible.builtin.git:
      repo: https://github.com/computer-geek64/homelab
      dest: '{{homelab_repo.path}}'
      depth: 1

  - name: Install Postgres
    ansible.builtin.import_tasks: postgres/install.yaml

  - name: Install Unbound
    ansible.builtin.import_tasks: unbound/install.yaml

  - name: Install Nextcloud
    ansible.builtin.import_tasks: nextcloud/install.yaml

  - name: Install Gitea
    ansible.builtin.import_tasks: gitea/install.yaml

  - name: Install Jenkins
    ansible.builtin.import_tasks: jenkins/install.yaml

  - name: Install Uptime Kuma
    ansible.builtin.import_tasks: uptime_kuma/install.yaml

  - name: Install Wiki
    ansible.builtin.import_tasks: wiki/install.yaml

  - name: Install Planka
    ansible.builtin.import_tasks: planka/install.yaml

  - name: Unbound install cleanup
    ansible.builtin.import_tasks: unbound/install_cleanup.yaml

  - name: Postgres install cleanup
    ansible.builtin.import_tasks: postgres/install_cleanup.yaml

  - name: Remove repo temporary directory
    ansible.builtin.file:
      path: '{{homelab_repo.path}}'
      state: absent
