- name: Setup
  hosts: all
  tasks:
  - name: Load JSON config
    ansible.builtin.include_vars:
      name: config
      file: config.json
  - name: Create repo temporary directory
    ansible.builtin.tempfile:
      state: directory
    register: homelab_repo
  - name: Clone git repo
    ansible.builtin.git:
      repo: https://github.com/computer-geek64/homelab
      dest: '{{homelab_repo.path}}'
      depth: 1

- name: Install on Citadel
  hosts: Citadel
  tasks:
  - name: Create bootstrap Docker network
    community.docker.docker_network:
      name: homelab-bootstrap
      ipam_config:
      - subnet: 172.19.0.0/24
        ip_range: 172.19.0.0/24
        gateway: 172.19.0.1
      state: present

  - name: Install Postgres
    ansible.builtin.import_tasks: postgres/install.yaml

  - name: Install Unbound
    ansible.builtin.import_tasks: unbound/install.yaml

  - name: Install Heimdall
    ansible.builtin.import_tasks: heimdall/install.yaml

  - name: Install Nextcloud
    ansible.builtin.import_tasks: nextcloud/install.yaml

  - name: Install Gitea
    ansible.builtin.import_tasks: gitea/install.yaml

  - name: Install Jenkins
    ansible.builtin.import_tasks: jenkins/install.yaml

  - name: Install Uptime Kuma
    ansible.builtin.import_tasks: uptime_kuma/install.yaml

  - name: Install Wiki
    ansible.builtin.import_tasks: wiki/install.yaml

  - name: Install Planka
    ansible.builtin.import_tasks: planka/install.yaml

- name: Install on TGS
  hosts: TGS
  tasks:
  - name: Install Unbound
    ansible.builtin.import_tasks: unbound/install_secondary.yaml

- name: Install cleanup on Citadel
  hosts: Citadel
  tasks:
  - name: Unbound install cleanup
    ansible.builtin.import_tasks: unbound/install_cleanup.yaml

  - name: Postgres install cleanup
    ansible.builtin.import_tasks: postgres/install_cleanup.yaml

  - name: Remove bootstrap Docker network
    community.docker.docker_network:
      name: homelab-bootstrap
      state: absent

- name: Teardown
  hosts: all
  tasks:
  - name: Remove repo temporary directory
    ansible.builtin.file:
      path: '{{homelab_repo.path}}'
      state: absent
