- name: Setup
  hosts: all
  tasks:
  - name: Load JSON config
    ansible.builtin.include_vars:
      name: config
      file: config.json
  - name: Create repo temporary directory
    ansible.builtin.tempfile:
      state: directory
    register: homelab_repo
  - name: Clone git repo
    ansible.builtin.git:
      repo: https://github.com/computer-geek64/homelab
      dest: '{{homelab_repo.path}}'
      depth: 1

- name: Start on Citadel
  hosts: Citadel
  tasks:
  - name: docker-compose up
    environment:
      WIKI_POSTGRES_PASSWORD: '{{config.wiki_postgres_password}}'
      PLANKA_POSTGRES_PASSWORD: '{{config.planka_postgres_password}}'
      PLANKA_SECRET_KEY: '{{config.planka_secret_key}}'
      DNS_POSTGRES_PASSWORD: '{{config.dns_postgres_password}}'
    ansible.builtin.docker_compose:
      project_name: homelab
      project_src: '{{homelab_repo.path}}'
      state: present

- name: Start on TGS
  hosts: TGS
  tasks:
  - name: Start Unbound Docker container
    community.docker.docker_container:
      name: unbound
      image: unbound:latest
      restart_policy: unless-stopped
      env:
        VPN_DNS: 'true'
        POSTGRES_HOST: '{{hostvars["Citadel"].vpn_ip}}'
        DNS_POSTGRES_PASSWORD: '{{config.dns_postgres_password}}'
      volumes:
      - /etc/localtime:/etc/localtime:ro
      network_mode: host
      keep_volumes: false
      state: started
  - name: Wait for Unbound to come online
    ansible.builtin.wait_for:
      host: localhost
      port: 53
      state: started

- name: Teardown
  hosts: all
  tasks:
  - name: Remove repo temporary directory
    ansible.builtin.file:
      path: '{{homelab_repo.path}}'
      state: absent
