- name: Load configuration
  hosts: citadel
  tasks:
  - name: Load JSON config
    ansible.builtin.include_vars:
      name: config
      file: config.json
  - name: Create repo temporary directory
    ansible.builtin.tempfile:
      state: directory
    register: homelab_repo
  - name: Clone git repo
    ansible.builtin.git:
      repo: https://github.com/computer-geek64/homelab
      dest: '{{homelab_repo.path}}'
      depth: 1

  - name: Uninstall Postgres
    ansible.builtin.import_tasks: postgres/uninstall.yaml

  - name: Install Nextcloud
    ansible.builtin.import_tasks: nextcloud/uninstall.yaml

  - name: Install Gitea
    ansible.builtin.import_tasks: gitea/uninstall.yaml

  - name: Uninstall Planka
    ansible.builtin.import_tasks: planka/uninstall.yaml

  - name: Uninstall Uptime Kuma
    ansible.builtin.import_tasks: uptime_kuma/uninstall.yaml

  - name: Uninstall Jenkins
    ansible.builtin.import_tasks: jenkins/uninstall.yaml

  - name: Uninstall Gitea
    ansible.builtin.import_tasks: gitea/uninstall.yaml

  - name: Uninstall Postgres
    ansible.builtin.import_tasks: postgres/uninstall.yaml

  - name: Remove repo temporary directory
    ansible.builtin.file:
      path: '{{homelab_repo.path}}'
      state: absent
