- name: Create Heimdall Postgres user
  community.postgresql.postgresql_user:
    login_host: localhost
    login_user: postgres
    login_password: '{{config.postgres_password}}'
    login_db: postgres
    name: heimdall
    password: '{{config.heimdall_postgres_password}}'
    state: present
- name: Create Heimdall Postgres database
  community.postgresql.postgresql_db:
    login_host: localhost
    login_user: postgres
    login_password: '{{config.postgres_password}}'
    maintenance_db: postgres
    name: heimdall
    owner: heimdall
    state: present

- name: Create Heimdall Docker volume
  vars:
    volume_name: homelab-heimdall-data
  ansible.builtin.import_tasks: ../util/create_docker_volume.yaml
- name: Start Heimdall Docker container
  community.docker.docker_container:
    name: homelab-heimdall-bootstrap
    image: linuxserver/heimdall:2.5.4
    pull: true
    env:
      APP_NAME: Homelab
      APP_URL: https://homelab.net
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: '5432'
      DB_DATABASE: heimdall
      DB_USERNAME: heimdall
      DB_PASSWORD: '{{config.heimdall_postgres_password}}'
    volumes:
    - homelab-heimdall-data:/config
    - /etc/localtime:/etc/localtime:ro
    networks:
    - name: homelab-bootstrap
    published_ports:
    - 8000:443
    dns_servers:
    - 172.19.0.1
    auto_remove: true
    keep_volumes: false
    state: started
- name: Wait for Heimdall to come online
  ansible.builtin.wait_for:
    host: localhost
    port: 8000
    state: started
- name: Wait for confirmation
  ansible.builtin.pause:
    prompt: Go to https://homelab.net and finish Heimdall setup

- name: Stop Heimdall Docker container
  community.docker.docker_container:
    name: homelab-heimdall-bootstrap
    state: absent
