# docker-compose.yaml

services:
  gitea:
    container_name: gitea
    image: gitea/gitea:1.18
    depends_on:
    - postgres
    restart: unless-stopped
    environment:
      GITEA__database__DB_TYPE: postgres
      GITEA__database__HOST: postgres
      GITEA__database__NAME: gitea
      GITEA__database__USER: gitea
      GITEA__database__PASSWD: ${POSTGRES_PASSWORD}
      GITEA__server__HTTP_PORT: '10003'
      GITEA__server__ROOT_URL: https://gitea.homelab.net
      GITEA__server__OFFLINE_MODE: 'true'
      GITEA__server__DISABLE_SSH: 'true'
      GITEA__mailer__ENABLED: 'true'
      GITEA__mailer__SMTP_ADDR: ${SMTP_ADDRESS}
      GITEA__mailer__SMTP_PORT: ${SMTP_PORT}
      GITEA__mailer__USER: ${SMTP_USER}
      GITEA__mailer__PASSWD: ${SMTP_PASSWORD}
      GITEA__mailer__FROM: ${SMTP_FROM_ADDRESS}
      GITEA__webhook__ALLOWED_HOST_LIST: '*'
      GITEA__webhook__SKIP_TLS_VERIFY: 'true'
      APP_NAME: Gitea
    volumes:
    - type: volume
      source: gitea-data
      target: /data
    - type: bind
      source: /etc/localtime
      target: /etc/localtime
      read_only: true
    networks:
    - gitea
    ports:
    - 127.0.0.1:10003:10003
  postgres:
    container_name: gitea-postgres
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_USER: gitea
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: gitea
    volumes:
    - type: volume
      source: postgres-data
      target: /var/lib/postgresql/data
    - type: bind
      source: /etc/localtime
      target: /etc/localtime
      read_only: true
    networks:
    - gitea

volumes:
  gitea-data:
    name: gitea-data
    external: true
  postgres-data:
    name: gitea-postgres-data
    external: true

networks:
  gitea:
    name: gitea
    ipam:
      config:
      - subnet: 172.19.0.0/24
        ip_range: 172.19.0.0/24
        gateway: 172.19.0.1
