- name: Create Gitea Postgres user
  community.postgresql.postgresql_user:
    login_host: localhost
    login_user: postgres
    login_password: '{{config.postgres_password}}'
    login_db: postgres
    name: gitea
    password: '{{config.gitea_postgres_password}}'
    state: present
- name: Create Gitea Postgres database
  community.postgresql.postgresql_db:
    login_host: localhost
    login_user: postgres
    login_password: '{{config.postgres_password}}'
    maintenance_db: postgres
    name: gitea
    owner: gitea
    state: present

- name: Create Gitea Docker volume
  vars:
    volume_name: homelab-gitea-data
  ansible.builtin.import_tasks: ../util/create_docker_volume.yaml
- name: Start Gitea Docker container
  community.docker.docker_container:
    name: homelab-gitea-bootstrap
    image: gitea/gitea:1.18
    pull: true
    env:
      GITEA__database__DB_TYPE: postgres
      GITEA__database__HOST: postgres
      GITEA__database__NAME: gitea
      GITEA__database__USER: gitea
      GITEA__database__PASSWD: '{{config.gitea_postgres_password}}'
      GITEA__server__HTTP_PORT: '8002'
      GITEA__server__ROOT_URL: https://gitea.homelab.net
      GITEA__server__OFFLINE_MODE: 'true'
      GITEA__server__DISABLE_SSH: 'true'
      GITEA__mailer__ENABLED: 'true'
      GITEA__mailer__PROTOCOL: smtp+starttls
      GITEA__mailer__SMTP_ADDR: in-v3.mailjet.com
      GITEA__mailer__SMTP_PORT: '587'
      GITEA__mailer__USER: '{{config.smtp_username}}'
      GITEA__mailer__PASSWD: '{{config.smtp_password}}'
      GITEA__mailer__FROM: '"Gitea" <gitea@ashishdsouza.com>'
      APP_NAME: Gitea
    volumes:
    - homelab-gitea-data:/data
    - /etc/localtime:/etc/localtime:ro
    networks:
    - name: homelab-bootstrap
    published_ports:
    - 8002:8002
    dns_servers:
    - 172.19.0.1
    auto_remove: true
    keep_volumes: false
    state: started
- name: Wait for Gitea to come online
  ansible.builtin.wait_for:
    host: localhost
    port: 8002
    state: started
- name: Wait for confirmation
  ansible.builtin.pause:
    prompt: Go to https://gitea.homelab.net and finish Gitea setup

- name: Stop Gitea Docker container
  community.docker.docker_container:
    name: homelab-gitea-bootstrap
    state: absent
