- name: Create Wiki Postgres user
  community.postgresql.postgresql_user:
    login_host: localhost
    login_user: postgres
    login_password: '{{config.postgres_password}}'
    login_db: postgres
    name: wiki
    password: '{{config.wiki_postgres_password}}'
    state: present
- name: Create Wiki Postgres database
  community.postgresql.postgresql_db:
    login_host: localhost
    login_user: postgres
    login_password: '{{config.postgres_password}}'
    maintenance_db: postgres
    name: wiki
    owner: wiki
    state: present

- name: Start Wiki Docker container
  community.docker.docker_container:
    name: homelab-wiki-bootstrap
    image: requarks/wiki:latest
    pull: true
    env:
      DB_TYPE: postgres
      DB_HOST: postgres
      DB_PORT: '5432'
      DB_USER: wiki
      DB_PASS: '{{config.wiki_postgres_password}}'
      DB_NAME: wiki
    volumes:
    - /etc/localtime:/etc/localtime:ro
    networks:
    - name: homelab-postgres-bootstrap
    published_ports:
    - 8005:3000
    auto_remove: true
    keep_volumes: false
    state: started
- name: Wait for Wiki to come online
  ansible.builtin.wait_for:
    host: localhost
    port: 8005
    state: started
- name: Wait for confirmation
  ansible.builtin.pause:
    prompt: Go to https://wiki.homelab.net and finish Wiki setup

- name: Stop Wiki Docker container
  community.docker.docker_container:
    name: homelab-wiki-bootstrap
    state: absent
