- name: Create docker volume bind mount directory
  become: true
  ansible.builtin.file:
    path: '{{config.docker_volumes_dir}}/{{volume_name}}'
    state: directory
- name: Create docker volume
  community.docker.docker_volume:
    volume_name: '{{volume_name}}'
    driver: local
    driver_options:
      type: none
      o: bind
      device: '{{config.docker_volumes_dir}}/{{volume_name}}'
    state: present
