- name: Create Uptime Kuma Docker volume
  vars:
    volume_name: homelab-uptime-kuma-data
  ansible.builtin.import_tasks: ../util/create_docker_volume.yaml
- name: Start Uptime Kuma Docker container
  community.docker.docker_container:
    name: homelab-uptime-kuma-bootstrap
    image: louislam/uptime-kuma:1.19.2
    pull: true
    volumes:
    - homelab-uptime-kuma-data:/app/data
    - /etc/localtime:/etc/localtime:ro
    networks:
    - homelab-bootstrap
    published_ports:
    - 8004:3001
    dns_servers:
    - 172.19.0.1
    auto_remove: true
    keep_volumes: false
    state: started
- name: Wait for Uptime Kuma to come online
  ansible.builtin.wait_for:
    host: localhost
    port: 8004
    state: started
- name: Wait for confirmation
  ansible.builtin.pause:
    prompt: Go to https://uptime-kuma.homelab.net and finish Uptime Kuma setup

- name: Stop Uptime Kuma Docker container
  community.docker.docker_container:
    name: homelab-uptime-kuma-bootstrap
    state: absent
