watch:
  schedule: 0 9,21 * * *
  jitter: 30s
  firstCheckNotif: false
  runOnStartup: true
  healthchecks:
    baseURL: https://healthchecks.homelab.net/ping/
    uuid: 482441cf-33cc-45c0-9923-99d425cec23e
notif:
  ntfy:
    endpoint: https://ntfy.homelab.net
    topic: diun
    priority: 3
    tags:
      - whale
providers:
  docker: true
