- name: Pull Ubuntu Docker image
  community.docker.docker_image:
    name: 'docker.io/library/ubuntu'
    tag: latest
    source: pull
    force_source: true
    state: present

- name: Build Unbound Docker image
  community.docker.docker_image:
    name: unbound
    build:
      path: '{{homelab_repo.path}}/unbound'
    source: build
    force_source: true
    state: present
- name: Start Unbound Docker container
  community.docker.docker_container:
    name: homelab-unbound-bootstrap
    image: unbound:latest
    env:
      DNS_POSTGRES_PASSWORD: '{{config.dns_postgres_password}}'
    volumes:
    - /etc/localtime:/etc/localtime:ro
    network_mode: host
    auto_remove: true
    keep_volumes: false
    state: started
- name: Wait for Unbound to come online
  ansible.builtin.wait_for:
    host: localhost
    port: 53
    state: started
- name: Wait for confirmation
  ansible.builtin.pause:
    prompt: Change DNS resolver on client machine to point to this host
