- name: Uninstall jenkins
  hosts: localhost
  tasks:
  - name: Remove jenkins docker volume
    vars:
      volume_name: homelab-jenkins-data
    ansible.builtin.import_tasks: ../util/remove_docker_volume.yaml
