- name: Install Unbound
  hosts: Moria
  tasks:
  - name: Create temporary build directory
    ansible.builtin.tempfile:
      state: directory
    register: build_dir
  - name: Copy build files to build directory
    ansible.builtin.copy:
      src: build/
      dest: '{{build_dir.path}}'
      mode: preserve

  - name: Build Unbound Docker image
    community.docker.docker_image:
      name: unbound
      tag: latest
      build:
        path: '{{build_dir.path}}'
        pull: true
      source: build
      force_source: true
      state: present

  - name: Remove temporary build directory
    ansible.builtin.file:
      path: '{{build_dir.path}}'
      state: absent

  - name: Read homelab config
    ansible.builtin.slurp:
      src: '{{ansible_user_dir}}/.homelab.json'
    register: homelab_config_file
  - name: Set homelab_config variable
    ansible.builtin.set_fact:
      homelab_config: '{{homelab_config_file.content|b64decode|from_json}}'

  - name: Insert into Postgres table service
    community.postgresql.postgresql_query:
      login_host: '{{homelab_config.database.host}}'
      login_user: '{{homelab_config.database.user}}'
      login_password: '{{homelab_config.database.password}}'
      db: '{{homelab_config.database.name}}'
      query: 'INSERT INTO service (name, host, config) VALUES (%s, %s, %s) ON CONFLICT DO NOTHING;'
      positional_args:
      - '{{item.name}}'
      - '{{item.host}}'
      - '{{item.config}}'
    with_items:
    - {name: unbound_vpn, host: '{{ansible_hostname}}', config: null}
  - name: Insert into Postgres table service_port
    community.postgresql.postgresql_query:
      login_host: '{{homelab_config.database.host}}'
      login_user: '{{homelab_config.database.user}}'
      login_password: '{{homelab_config.database.password}}'
      db: '{{homelab_config.database.name}}'
      query: 'INSERT INTO service_port (service, port, domain, reverse_proxy, reverse_proxy_port) VALUES (%s, %s, %s, %s, %s) ON CONFLICT DO NOTHING;'
      positional_args:
      - '{{item.service}}'
      - '{{item.port}}'
      - '{{item.domain}}'
      - '{{item.reverse_proxy}}'
      - '{{item.reverse_proxy_port}}'
    with_items:
    - {service: unbound_vpn, port: 53, domain: null, reverse_proxy: null, reverse_proxy_port: null}
