- name: Start Uptime Kuma
  hosts: Moria
  tasks:
  - name: Start Uptime Kuma Docker container
    community.docker.docker_container:
      name: uptime-kuma
      image: louislam/uptime-kuma:1.23.16
      restart_policy: unless-stopped
      labels:
        autoheal: 'true'
        diun.enable: 'true'
        diun.watch_repo: 'true'
        diun.notify_on: new;update
        diun.sort_tags: semver
        diun.max_tags: '1'
        diun.include_tags: '^\d+\.\d+\.\d+$'
      env:
        NODE_EXTRA_CA_CERTS: /certs/homelab_ca.crt
      volumes:
      - uptime-kuma-data:/app/data
      - /data/certs/homelab_ca.crt:/certs/homelab_ca.crt:ro
      - /etc/localtime:/etc/localtime:ro
      published_ports:
      - 127.0.0.1:10001:3001
      keep_volumes: false
      state: started
