- name: Start Jenkins
  hosts: Moria
  tasks:
  - name: Start Jenkins Docker container
    community.docker.docker_container:
      name: jenkins
      image: jenkins/jenkins:lts-jdk11
      restart_policy: unless-stopped
      env:
        JAVA_OPTS: -Xmx384m
      volumes:
      - jenkins-data:/var/jenkins_home
      - /etc/localtime:/etc/localtime:ro
      published_ports:
      - 127.0.0.1:10004:8080
      keep_volumes: false
      state: started

