watch:
  schedule: 0 8,20 * * *
  jitter: 30s
  firstCheckNotif: false
  runOnStartup: true
  healthchecks:
    baseURL: https://healthchecks.homelab.net/ping/
    uuid: bedf93f3-e8d2-46ab-85c8-bb52675273ab
notif:
  ntfy:
    endpoint: https://ntfy.homelab.net
    topic: diun
    priority: 3
    tags:
      - whale
providers:
  docker: true
