- name: Install AdGuard Home
  hosts: Lothlorien
  tasks:
    - name: Create AdGuard config Docker volume directory
      become: true
      ansible.builtin.file:
        path: /data/adguard-config
        state: directory
    - name: Create AdGuard config Docker volume
      community.docker.docker_volume:
        volume_name: adguard-config
        driver: local
        driver_options:
          type: none
          o: bind
          device: /data/adguard-config
        state: present
    - name: Create AdGuard data Docker volume directory
      become: true
      ansible.builtin.file:
        path: /data/adguard-data
        state: directory
    - name: Create AdGuard data Docker volume
      community.docker.docker_volume:
        volume_name: adguard-data
        driver: local
        driver_options:
          type: none
          o: bind
          device: /data/adguard-data
        state: present

    - name: Copy Nginx config file for AdGuard
      become: true
      ansible.builtin.copy:
        src: conf/nginx.conf
        dest: /data/nginx-config/adguard.conf
        mode: preserve

    - name: Read homelab config
      ansible.builtin.slurp:
        src: '{{ansible_user_dir}}/.homelab.json'
      register: homelab_config_file
    - name: Set homelab_config variable
      ansible.builtin.set_fact:
        homelab_config: '{{homelab_config_file.content|b64decode|from_json}}'

    - name: Insert into Postgres table service
      community.postgresql.postgresql_query:
        login_host: '{{homelab_config.database.host}}'
        login_user: '{{homelab_config.database.user}}'
        login_password: '{{homelab_config.database.password}}'
        login_db: '{{homelab_config.database.name}}'
        query: 'INSERT INTO service (name, host, source, config) VALUES (%s, %s, %s, %s) ON CONFLICT DO NOTHING;'
        positional_args:
          - '{{item.name}}'
          - '{{item.host}}'
          - '{{item.source}}'
          - '{{item.config}}'
      with_items:
        - {name: adguard_lothlorien, host: '{{ansible_hostname}}', source: github/computer-geek64/homelab/master/lothlorien/adguard, config: null}
    - name: Insert into Postgres table service_port
      community.postgresql.postgresql_query:
        login_host: '{{homelab_config.database.host}}'
        login_user: '{{homelab_config.database.user}}'
        login_password: '{{homelab_config.database.password}}'
        login_db: '{{homelab_config.database.name}}'
        query: 'INSERT INTO service_port (service, port, domain, reverse_proxy, reverse_proxy_port) VALUES (%s, %s, %s, %s, %s) ON CONFLICT DO NOTHING;'
        positional_args:
          - '{{item.service}}'
          - '{{item.port}}'
          - '{{item.domain}}'
          - '{{item.reverse_proxy}}'
          - '{{item.reverse_proxy_port}}'
      with_items:
        - {service: adguard_lothlorien, port: 53, domain: null, reverse_proxy: null, reverse_proxy_port: null}
        - {service: adguard_lothlorien, port: 10007, domain: adguard-dsatp58.homelab.net, reverse_proxy: nginx_lothlorien, reverse_proxy_port: 443}
    - name: Insert into Postgres table service_data
      community.postgresql.postgresql_query:
        login_host: '{{homelab_config.database.host}}'
        login_user: '{{homelab_config.database.user}}'
        login_password: '{{homelab_config.database.password}}'
        login_db: '{{homelab_config.database.name}}'
        query: 'INSERT INTO service_data (service, data_name, storage_type, source) VALUES (%s, %s, %s, %s) ON CONFLICT DO NOTHING;'
        positional_args:
          - '{{item.service}}'
          - '{{item.data_name}}'
          - '{{item.storage_type}}'
          - '{{item.source}}'
      with_items:
        - {service: adguard_lothlorien, data_name: config, storage_type: docker, source: adguard-config}
        - {service: adguard_lothlorien, data_name: data, storage_type: docker, source: adguard-data}
